new SimGroup(LightPrototypesGroup) {
	canSave = "1";
	canSaveDynamicFields = "1";
	enabled = "1";

	// light protototypes should disabled and hidden. Like this:
	// radius = "0";
	// isEnabled = "0";
	// hidden = "1";

	singleton PointLight(Green_PointlightPrototype) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
		color = "0 1 0 1";
		brightness = "10";
		castShadows = "0";
		priority = "1";
		animate = "0";
		animationPeriod = "1";
		animationPhase = "1";
		flareScale = "1";
		attenuationRatio = "0 1 1";
		shadowType = "DualParaboloidSinglePass";
		texSize = "512";
		overDarkFactor = "2000 1000 500 100";
		shadowDistance = "400";
		shadowSoftness = "0.15";
		numSplits = "1";
		logWeight = "0.91";
		fadeStartDistance = "0";
		lastSplitTerrainOnly = "0";
		representedInLightmap = "0";
		shadowDarkenColor = "0 0 0 -1";
		includeLightmappedGeometryInShadow = "0";
		canSave = "1";
		canSaveDynamicFields = "1";
	};

	singleton PointLight(Red_PointlightPrototype) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
		color = "1 0 0 1";
		brightness = "3";
		castShadows = "0";
		priority = "1";
		animate = "0";
		animationPeriod = "1";
		animationPhase = "1";
		flareScale = "1";
		attenuationRatio = "0 1 1";
		shadowType = "DualParaboloidSinglePass";
		texSize = "512";
		overDarkFactor = "2000 1000 500 100";
		shadowDistance = "400";
		shadowSoftness = "0.15";
		numSplits = "1";
		logWeight = "0.91";
		fadeStartDistance = "0";
		lastSplitTerrainOnly = "0";
		representedInLightmap = "0";
		shadowDarkenColor = "0 0 0 -1";
		includeLightmappedGeometryInShadow = "0";
		canSave = "1";
		canSaveDynamicFields = "1";
	};

	singleton PointLight(FirePointLight) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
    	color = "1 0.3 0 0.1";
      brightness = "0.1";
      castShadows = "1";
      priority = "1";
      animate = "0";
      animationPeriod = "1.5";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.5";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "125.504 383.853 1025.88";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
      hidden = "1";
   };

 singleton PointLight(Lamppost_Light) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.450000 0.050000 1";
      brightness = "0.02";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.5";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "0 0 0";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

   singleton PointLight(Torch_light) {
		radius = "30";
		isEnabled = "1";
		hidden = "1";
		color = "1 0.45 0 1.0";
		brightness = "0.03";
		castShadows = "0";
		priority = "1";
		animate = "1";
		animationPeriod = "1.5";
		animationPhase = "1";
		flareScale = "1";
		attenuationRatio = "0 1 1";
		shadowType = "DualParaboloid";
		texSize = "512";
		overDarkFactor = "2000 1000 500 100";
		shadowDistance = "400";
		shadowSoftness = "0.075";
		numSplits = "1";
		logWeight = "0.91";
		fadeStartDistance = "0";
		lastSplitTerrainOnly = "0";
		representedInLightmap = "0";
		shadowDarkenColor = "0 0 0 -1";
		includeLightmappedGeometryInShadow = "0";
		position = "0 0 0";
		rotation = "1 0 0 0";
		canSave = "1";
		canSaveDynamicFields = "1";
   };

    singleton PointLight(Lamppost_Light_2) {
            radius = "0";
            isEnabled = "0";
            hidden = "1";
      color = "1.000000 0.627451 0.427451 1";
      brightness = "0.1";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.15";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-699.726 647.529 1204.93";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

   singleton PointLight(bonfire_light) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.350000 0.050000 1";
      brightness = "0.1";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationType = "FireLightAnim";
      animationPeriod = "1.35";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "1024";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.5";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "0 0 0";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

	 singleton PointLight(bonfire_light2) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
			color = "0.500000 0.350000 0.050000 0.5";
			brightness = "0.01";
			castShadows = "0";
			priority = "1";
			animate = "1";
			animationType = "FireLightAnim";
			animationPeriod = "1.35";
			animationPhase = "1";
			flareScale = "1";
			attenuationRatio = "0 1 1";
			shadowType = "DualParaboloidSinglePass";
			texSize = "1024";
			overDarkFactor = "2000 1000 500 100";
			shadowDistance = "400";
			shadowSoftness = "0.5";
			numSplits = "1";
			logWeight = "0.91";
			fadeStartDistance = "0";
			lastSplitTerrainOnly = "0";
			representedInLightmap = "0";
			shadowDarkenColor = "0 0 0 -1";
			includeLightmappedGeometryInShadow = "0";
			position = "0 0 0";
			rotation = "1 0 0 0";
			canSave = "1";
			canSaveDynamicFields = "1";
	 };

   singleton PointLight(Forge_Light) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1 0.31 0 0.51";
      brightness = "0.35";
      castShadows = "0";
      priority = "1";
      animate = "1";
	  animationType = "FireLightAnim";
      animationPeriod = "1.35";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.5";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-704.427 656.426 1202.28";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

 singleton PointLight(Trailer_light01) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.627451 0.427451 1";
      brightness = "0.15";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.15";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-699.726 647.529 1204.93";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

 singleton PointLight(Trailer_light02) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.627451 0.427451 1";
      brightness = "0.8";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.15";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-699.726 647.529 1204.93";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

 singleton PointLight(Trailer_light03) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.627451 0.427451 1";
      brightness = "0.8";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.15";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-699.726 647.529 1204.93";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

 singleton PointLight(Trailer_light04) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.627451 0.427451 1";
      brightness = "0.8";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.15";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-699.726 647.529 1204.93";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

 singleton PointLight(Trailer_light05) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.627451 0.427451 1";
      brightness = "0.8";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.15";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-699.726 647.529 1204.93";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

 singleton PointLight(Trailer_light06) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "1.000000 0.627451 0.427451 1";
      brightness = "0.8";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.15";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "-699.726 647.529 1204.93";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

 singleton PointLight(Ferryman_Light01) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "0.9500000 0.550000 0.550000 1";
      brightness = "0.1";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.5";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "0 0 0";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };
   
 singleton PointLight(Ferryman_Light02) {
		radius = "0";
		isEnabled = "0";
		hidden = "1";
      color = "0.6000000 0.720000 0.980000 1";
      brightness = "0.25";
      castShadows = "0";
      priority = "1";
      animate = "1";
      animationPeriod = "1";
      animationPhase = "1";
      flareScale = "1";
      attenuationRatio = "0 1 1";
      shadowType = "DualParaboloidSinglePass";
      texSize = "512";
      overDarkFactor = "2000 1000 500 100";
      shadowDistance = "400";
      shadowSoftness = "0.5";
      numSplits = "1";
      logWeight = "0.91";
      fadeStartDistance = "0";
      lastSplitTerrainOnly = "0";
      representedInLightmap = "0";
      shadowDarkenColor = "0 0 0 -1";
      includeLightmappedGeometryInShadow = "0";
      position = "0 0 0";
      rotation = "1 0 0 0";
      canSave = "1";
      canSaveDynamicFields = "1";
   };

};
